<?php

namespace App\Tests\Service;

use App\Domain\Email;
use App\Service\EmailCheckerServiceAdapter;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class EmailCheckerServiceAdapterTest extends KernelTestCase
{

    private $emailChecker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::bootKernel([
            'environment' => 'test'
        ]);
        $this->emailChecker = self::$container->get('test.' . EmailCheckerServiceAdapter::class);
    }


    public function testItFindDisposableEmail()
    {
        $email = new Email('john@mailinator.com');


        $this->assertTrue($this->emailChecker->checkEmailIfDisposable($email));
    }

    public function testItFindCorrectEmail()
    {
        $email = new Email('adam@gmail.com');

        $this->assertFalse($this->emailChecker->checkEmailIfDisposable($email));
    }
}
