services:
  _defaults:
    public: true

  'test.App\Service\EmailCheckerServiceAdapter': '@App\Service\EmailCheckerServiceAdapter'
  test.App\Domain\ShopProductRepositoryInterface: '@App\Domain\ShopProductRepositoryInterface'
